FROM arm32v7/node:lts-alpine
MAINTAINER Oscar Medina <oscmedgon@gmail.com>
LABEL version='7.46.0'
LABEL description='Heroku CLI packaged on alpine linux for arm32v7 architecture'

ENV HEROKU_CLI_VERSION '7.46.0'
RUN npm install -g heroku@$HEROKU_CLI_VERSION

