version: '3'

services:
  lhci:
    container_name: lhci
    image: pihole/pihole:latest
    privileged: true
    ports:
    - 80:80
    environment:
      TZ: 'CET'
      WEBPASSWORD: '96QdVz5F'
      DNS1: "10.0.1.2#5300"
      DNS2: '1.1.1.1'
      ServerIP: '192.168.1.254'
    network_mode: host
    depends_on:
      - dnscrypt
    volumes:
      - pihole_config:/etc/pihole/
      - dnsmasq_config:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  # set pihole DNS1 and DNS2 service variables to 127.0.0.1#5053 to use dnscrypt-proxy for upstream DNS
  dnscrypt:
    container_name: dnscrypt-proxy
    image: klutchell/dnscrypt-proxy:latest
    volumes:
      - './dnscrypt-proxy:/config'
    networks:
      pihole_net:
        ipv4_address: 10.0.1.2
    dns:
      - 1.1.1.1
    ports:
      - "5300:5300/udp"
      - "5300:5300/tcp"
#  wireguard:
#    image: linuxserver/wireguard
#    container_name: wireguard
#    cap_add:
#      - NET_ADMIN
#      - SYS_MODULE
#    environment:
#      - PUID='1000'
#      - PGID='1000'
#      - TZ='CET'
#      - SERVERURL='odin.ciUtils.com'
#      - PEERS='2'
#      - PEERDNS='auto'
#      - INTERNAL_SUBNET='10.13.13.0'
#    volumes:
#      - wireguard_config:/config
#      - wireguard_lib:/lib/modules
#      - /usr/src:/usr/src
#    ports:
#      - 51820:51820/udp
#    networks:
#      pihole_net:
#        ipv4_address: 10.0.1.4
#    sysctls:
#      - net.ipv4.conf.all.src_valid_mark=1
#    restart: unless-stopped
volumes:
  pihole_config:
  dnsmasq_config:
#  wireguard_config:
#  wireguard_lib:
networks:
  pihole_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
